### ISSUE TITLE
Cleanup branches

### ISSUE THREAD

**Issue by mitchellcash** [PaycoinFoundation/paycoin#106]
We should cleanup the branches.
As mentioned in the contribution guidelines developers work on their own forks so there should be no need for branches on the main repo.
I would accept version branches i.e. branch for 0.2.0.0 and another for 0.3.0.0 but outside of that we should keep it clean and consistent with contribution guidelines.
Also I don't think it looks too good having 16 branches sitting there with the majority being stale at this point.

**Comment by IngCr3at1on** [comment]
I agree, I've been hesitant to delete the old/dead branches without first discussing it with someone. @PaycoinMaster @xmk3 your opinions?

**Comment by HyperCommNet** [comment]
I Agree with this

**Comment by IngCr3at1on** [comment]
Currently all but the master branch are random patches and should have been deleted when they were merged into master. I'll gladly delete all of these assuming there's no argument against it (I'll give @xmk3 a bit to respond lol)

**Comment by IngCr3at1on** [comment]
Spoke to @xmk3 he's for it. I forgot you could do this from the branches menu on github (used to be you had to push from git to delete a branch); you want to clean those up @PaycoinMaster or should I?

**Comment by mitchellcash** [comment]
Thanks everyone. I'm all for making a 0.3.0.0 branch, thoughts?

**Comment by IngCr3at1on** [comment]
Sure? Do we need it? lol

**Comment by mitchellcash** [comment]
Not really, someone might find it useful if they needed to build from source an earlier version and I notice Bitcoin does it for all major releases from 0.8
But someone could also just use the tag 0.3.0.0 so probably a bit redundant. Happy to not do it if you don't think it's needed.

**Comment by IngCr3at1on** [comment]
Generally the main reason for having a version branch is if you are going to be supporting multiple versions.

A good example is how Android has a branch for each major version (KitKat, Lollipop, etc); these have numeric tags for each release but as they go through and fix certain bugs and do sub versions they add that code to the version branch instead of a dev or master branch ((master itself is more or less the development branch in the case of android).

Being that we don't/won't be supporting older versions I don't think this is necessary personally but I really have no strong feelings one way or the other.

--

I deleted all of the merged branches but I left the stale ones, personally I think all of them can go (including the one marked testnet as we're not using that branch and it's extremely out of date).

**Comment by mitchellcash** [comment]
I see your point. I'm happy to leave out version branches until such time support for older versions is applicable.

Agree to remove stale branches.
I notice that you introduced a new branch yesterday?

**Comment by IngCr3at1on** [comment]
That branch was auto-created when I clicked the revert option from a PR. We can delete it after it's merged.

**Comment by mitchellcash** [comment]
Cool, thanks.

**Comment by IngCr3at1on** [comment]
All branches but master have been removed.
