### ISSUE TITLE
QT 3.3.1 Stuck at 85%

### ISSUE THREAD

**Issue by jaybeezy** [PaycoinFoundation/paycoin#486]
I upgraded my wallet to version 3.3.1 last week. It synced to 85% and now is stuck. I have tried with/without anti-virus on and have checked to ensure that the firewall is open for the app. Can you address this bug?

**Comment by IngCr3at1on** [comment]
@jaybeezy first I've heard of it. Could be peers related to be entirely honest; if you look at getpeerinfo (via the debug console) you can see the height of the connected peers, if some of them aren't synced that could be an issue otherwise I'm not sure off the top of my head. I'll try to sync a node for a test though.

**Comment by IngCr3at1on** [comment]
I am curious though; if this is an "upgrade" why are you resynching it (there was no reason to wipe your chain data it should have simply kept working with the new wallet)?

**Comment by IngCr3at1on** [comment]
@jaybeezy I left a node running over not it synced fully from 0 blocks. I expect your issue as I mentioned before is more related to your connected peers than the wallet itself.

**Comment by jaybeezy** [comment]
@IngCr3at1on  - You are correct, it was a peer issue. I reset the application and it finally synced after 48 hours. Issue is now resolved!
