### ISSUE TITLE
Paycoin as Peercoin fork; could it merge back into Peercoin?

### ISSUE THREAD

**Issue by RdeWilde** [PaycoinFoundation/paycoin#71]
I have more a question than an issue actually.

As Paycoin is a fork from Peercoin, would it be technically be possible to merge 'back' into Peercoin? Mainly it would be about preserving the blockchain and maintaining the wallet addresses and coins.

I have seen some people posting their "Peercoin/paycoin combi-wallet"-address, not sure what that is? Could those operate on the same network slowly merging back into each other or something (conversion on transaction of old coins into "new" coins)?

Ofcourse the community, capital, extra features, investors, future plans etc would be an issue, but that's out of scope. Would just like to know if it is possible at all :-)

**Comment by IngCr3at1on** [comment]
The matter of the combined wallet addresses is actually what some would call a bug.

Basically the original developers didn't change the code used to generate a paycoin address from that of peercoin so the addresses themselves are the same.

However being on 2 separate blockchains means that the coins from one blockchain won't be accepted by the other. You can essentially use the same address for both peercoin and paycoin whilst having them exist entirely separately on the 2 blockchains.

They can't be merged together because of the differences in the process block functions; peercoin still has running proof of work (which as you are aware is disabled in paycoin), PoW blocks would be instantly rejected by the paycoin network. Paycoin has primecontrollers which stake at a different rate than other nodes, this stake is checked when a node receives a transaction and subsequently any peercoin nodes would instantly refuse a prime stake transaction.

There are probably more reasons the two networks/blockchains are incompatible that I am not thinking of ATM.

To be perfectly honest it's been discussed that we should fix the paycoin addresses so that they are not the same as peercoin ones.

**Comment by mitchellcash** [comment]
Please close.
I don't think merging with Peercoin is really a solution to our problems nor possible. However, this did provoke an interesting thought on moving wallet addresses away from the Peercoin format. See issue #107 for further discussion.

**Comment by IngCr3at1on** [comment]
Agreed, further discussion on the matter can be continued in issue #107.
